export const data = [
  {
    title: "Họ và tên",
    dataIndex: "name",
    // hideInTable: true,
    hideInSearch: true,
  },
  {
    title: "Tên đăng nhập",
    dataIndex: "username",
  },
  {
    title: "Email",
    dataIndex: "email",
  },
  {
    title: "Bộ môn",
    dataIndex: "subject",
  },
  {
    title: "Vai trò",
    dataIndex: "role_id",
  },
  {
    title: "Ngày sinh",
    dataIndex: "dob",
    hideInSearch: true,
  },
  {
    title: "Số điện thoại",
    dataIndex: "phone",
  },
  {
    title: "Ngày tạo",
    dataIndex: "create_at",
    hideInSearch: true,
  },
  {
    title: "Ngày cập nhật",
    dataIndex: "update_at",
    hideInSearch: true,
  },
];

const dataSource2 = [
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
  {
    name: "Nguyễn Văn Nữ",
    username: "nuvamm",
    email: "gmail@gmail.com",
    subject: "CNTT",
    role_id: "GIAO_Vien",
    dob: "22/12/2000",
    phone: "38275047504",
    create_at: "22/2/2000",
    update_at: "12/4/2009",
  },
];

export { dataSource2 };
